version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    environment:
      - DJANGO_SECRET_KEY=902512fbfd6d99bf3591550b3e61325aeae1a4dc60cda1c564a7cf0ebec937bb
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_DB_URL=postgres://postgres:postgres@db/postgres
    ports:
      - "8000:8000"
    depends_on:
      - db
