# Generated by Django 3.1.4 on 2020-12-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('total', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Сумма')),
                ('contractor', models.CharField(max_length=128, verbose_name='Контрагент')),
                ('text', models.TextField(verbose_name='Текст заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
